### ISSUE TITLE
Solution doesn't match question in Lab 01 - Intro to R - Data Structures

### ISSUE THREAD

**Issue by tomdewildt** [SNAnalyst/SNA4DS#3]
The question in the "Data Structure" section of "Lab 01 - Intro to R" doesn't seem to match the actual solution as it also changes the `a` variable.

**Question**
_If I tell you to use the function as.matrix(), can you make these two variables into a matrix using cbind()?_

**My Solution**

```r
a <- 1:10
b <- LETTERS[1:10]

as.matrix(cbind(a, b))
```

**Actual Solution**

```r
a <- LETTERS[11:20]
b <- LETTERS[1:10]

m <- as.matrix(cbind(a, b))
```

**File**

https://github.com/SNAnalyst/SNA4DS/blob/549148ae75a404884490c753e84a4ae53fd14a61/inst/tutorials/lab01_IntroR/Intro_to_R_tutorial.Rmd#L944-L964

**Comment by czucca** [comment]
Solved! Thanks for reporting it!
